version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dwani_api
    ports:
      - "9000:9000" # Expose port 9000 for external access (Gemma model)
      - "8000:8000" # Expose port 8000 for internal FastAPI server (optional, can be removed if not needed externally)
    environment:
      - DWANI_API_BASE_URL_PDF=${DWANI_API_BASE_URL_PDF}
      - DWANI_API_BASE_URL_VISION=${DWANI_API_BASE_URL_VISION}
      - DWANI_API_BASE_URL_LLM=${DWANI_API_BASE_URL_LLM}
      - DWANI_API_BASE_URL_LLM_QWEN=${DWANI_API_BASE_URL_LLM_QWEN}
      - DWANI_API_BASE_URL_TTS=${DWANI_API_BASE_URL_TTS}
      - DWANI_API_BASE_URL_ASR=${DWANI_API_BASE_URL_ASR}
      - DWANI_API_BASE_URL_TRANSLATE=${DWANI_API_BASE_URL_TRANSLATE}
      - DWANI_API_BASE_URL_S2S=${DWANI_API_BASE_URL_S2S}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - dwani_network

networks:
  dwani_network:
    driver: bridge