services:
  dwani-api-server-nginx:
    build: .
    image: dwani/dwani-api-server-nginx
    ports:
      - "8080:8080"  # Maps host port 80 to container port 8080 (Nginx internal port)
    restart: unless-stopped
    # Optional: Add volumes for persistent logs if needed
    # volumes:
    #   - ./data:/data